### ISSUE TITLE
[STORY] View daily spend

### ISSUE THREAD

**Issue by nottsknight** [nottsknight/BasicDailyBudget#1]
**As an** app user
**I want to** view my daily budget
**so that** I can know how much I have to spend today.

**Comment by nottsknight** [comment]
# Task list

- [x] Set up data model
- [x] Create display screen
- [x] Connect display screen to model
