### ISSUE TITLE
[STORY] Set payday

### ISSUE THREAD

**Issue by nottsknight** [nottsknight/BasicDailyBudget#2]
**As an** app user
**I want to** specify my next payday
**so that** my available balance can be spread throughout the rest of the month

**Comment by nottsknight** [comment]
# Tasks

- [x] Create account update screen and viewmodel
- [x] Implement db update from update screen
- [x] Enable navigation between update and summary screens
